# Generated by Django 4.1.3 on 2022-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_attendance_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="papers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept", models.CharField(max_length=100)),
                ("paper", models.FileField(upload_to="static/")),
            ],
        ),
        migrations.CreateModel(
            name="papers1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept1", models.CharField(max_length=100)),
                ("paper1", models.URLField()),
            ],
        ),
    ]
