# Generated by Django 4.1.3 on 2022-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_papers_papers1"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="name",
            field=models.CharField(default="ABC", max_length=100),
        ),
    ]
